src/main/java/me/qoomon/maven/extension/gitversioning/VersioningPomReplacementMojo.java

When I do multi-threaded builds (mvn install -T4), I get the following NullPointer:
```
Caused by: java.lang.NullPointerException
at me.qoomon.maven.GAV.of (GAV.java:74)
at me.qoomon.maven.extension.gitversioning.VersioningPomReplacementMojo.execute (VersioningPomReplacementMojo.java:50)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
at …
```

Fix NullPointer during multi-threaded builds

---

src/main/java/me/qoomon/maven/gitversioning/ModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java
src/test/resources/testProjects/multiModuleProject/duplicate-artifactid-different-groupid/pom.xml
src/test/resources/testProjects/multiModuleProject/pom.xml

In a multimodel project, when the artifact id of 2 (sub)projects are the same, but the groupids are different, you get errors due to a collision.
- The virtualProjectModelCache now includes the groupid to fix this problem.
- An integration test is added to the this situation

Bugfix: project model collision

---

src/main/java/me/qoomon/gitversioning/GitRepoSituation.java
src/main/java/me/qoomon/gitversioning/GitUtil.java
src/main/java/me/qoomon/gitversioning/GitVersioning.java
src/test/java/me/qoomon/gitversioning/GitVersioningTest.java

Added support for commit date time to make the version sequential by using the placeholders 'datetime' or 'timestamp'. 
For example using the expression {datetime}-${commit.short} produces something like 20190521.011351-9abfd9d
Similarly, {timestamp}-${commit.short} produces 1558401231000-9abfd9d
Let me know if you like the additional feature or if you want me to change something.

Added support for commit date time to make the version sequential

---

README.md
src/main/java/me/qoomon/gitversioning/GitVersionDetails.java
src/main/java/me/qoomon/gitversioning/GitVersioning.java
src/main/java/me/qoomon/gitversioning/PropertyDescription.java
src/main/java/me/qoomon/gitversioning/PropertyValueDescription.java
src/main/java/me/qoomon/gitversioning/VersionDescription.java
src/main/java/me/qoomon/maven/gitversioning/Configuration.java
src/main/java/me/qoomon/maven/gitversioning/ModelProcessor.java
src/test/java/me/qoomon/gitversioning/GitVersioningTest.java
src/test/java/me/qoomon/maven/gitversioning/ConfigurationTest.java

This PR adds the capability to update properties values as well. This is relevant when working simultaneously on 2 dependent projects, as described in https://github.com/qoomon/maven-git-versioning-extension/issues/41.
This improvement allows to define configuration as follows:
```xml
<branch>
<pattern><![CDATA[feature/(?<feature>.+)]]></pattern>
<versionFormat>${version.release}-${feature}-SNAPSHOT</versionFormat>
<property>
<pattern>my.property.name</pattern>
<value>
<pattern><![CDATA[(?<propertyVersion>.+?)(-SNAPSHOT)]]></pattern>
<format>${propertyVersion}-${feature}-SNAPSHOT</format>
</value>
</property>
</branch>
```
In this example the property `my.property.name`, if exists, if it matches the pattern <projectVersion>-SNAPSHOT and if the current branch matches the pattern …

Add the capability to update properties values

---

src/main/java/me/qoomon/maven/gitversioning/ModelProcessor.java

Hi Bengt
I'm Alex, from Jetbrains team. 
Our users have some issues with your plugin, please consider https://youtrack.jetbrains.com/issue/IDEA-220311
Actually,  there were  an issue in previous idea versions (https://youtrack.jetbrains.com/issue/IDEA-200272), when sessionScope was not entered, mavenSession was not set and maven-git-versioning-extension simply was not executed with message "skip - no maven session present".
Now, it is being executed and this lead to resolve issues during project import
At the moment, it is quite hard from our side to catch patched model "on-the-fly".
I believe there can be an option to disable extension execution using command line properties, e.g. the same way it is done in jitver-maven-plugin
It would greatly helps in operations which do not require …

Added flag to skip model processing

---

README.md
src/main/java/me/qoomon/gitversioning/GitVersioning.java
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/gitversioning/GitUtilTest.java
src/test/java/me/qoomon/gitversioning/GitVersioningTest.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

Currently, tag rules are omitted if there is a branch available. This does not really make sense, as one hardly ever checks out a specific tag to create a build. I suggest to prefer the tag if there is a matching tag rule.
BTW, thank you for this great tool!

[FEATURE REQUEST] prefer tag rules over branch rules

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

Sorry to bother you again. I think the cli option `-Dversioning.preferTags=false` should override an
existing config option `<preferTags>true</preferTags>`, as similar behaviour can be observed if you set a tag or branch by cli option, causing existing branches and tags to be ignored.

fix (?): cli option should override config file

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

To align behavior to other maven plugins that use info level when skipping is enabled. And to get a warning free build.

Reduce log level to info

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

This allows the build to succeed without a Git repository, but with a warning.

don't error out on non-existant Git directories

---

README.md

I noticed that the placeholders for minute and second are singular in the [code](https://github.com/qoomon/maven-git-versioning-extension/blob/e4adc7ab1e454ebe92aaee18c9c1b877c59f40b9/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L553) (equivalent to the ones for year, month, day and hour) but are (I assume accidentally) documented as being plural in the README.
A very minor thing but it cost me a couple of minutes so having this corrected may save someone else the time :slightly_smiling_face:

Make 'minute' and 'second' singular instead of plural in the README

---

src/main/java/me/qoomon/maven/gitversioning/MavenUtil.java

Only write the new pom if it has changed. 
This prevents the maven jar plugin from recreating the jar if nothing has changed.

don't update pom if unchanged, prevents unnecessary rebuilds in maven

---

README.md
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

Having access to the main version components (i.e. major, minor as well as patch version), would allow us to use this extension in a setup with Tycho modules and their rather strict versioning scheme.

additional version component placeholders

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

The `${version.label.prefixed}` placeholder is [documented](https://github.com/qoomon/maven-git-versioning-extension/blob/c880f43b832bff689359f1316f7c870360a1db4a/README.md?plain=1#L160) but not implemented.
This PR provides the implementation.

Add support for the ${version.label.prefixed} placeholder

---

README.md
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

This PR introduces the placeholder `${build.timestamp}` generated from `MavenSession#getStartTime`. It has the same sub-placeholders like `${commit.timestamp}`.
The placeholder enables the possibility to build multiple artifacts with uncommited changes based on the same commit.
In my case we are building a set of rules as a zipped artifact for a ruleengine. The developers make local changes, build them uncommited and upload the artifact to a server to test the rules. Sometimes they need to upload multiple artifacts, based on the same commit but with different changes, to compare the results.
```xml
<ref type="branch">
<pattern><![CDATA[local/(?<feature>.+)]]></pattern>
<version>${ref.feature}-${build.timestamp.datetime}</version>
</ref>
```
Maven build command
`mvn clean verify …

Provide maven-build-timestamp as "commit.timestamp"-like placeholder "build.timestamp" 

---

README.md
src/main/java/me/qoomon/gitversioning/commons/GitUtil.java
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

This pull request adds the following capabilities to the qoomon extension
1. Ability to extract a number from the label (if the label is numeric) – note that this needs to be used with care as a non-numeric label fed into this will cause a build failure – this is because we wish to use (on master) versions of the form 1.2.3-456 (where 456 is auto-generated based on previous build number – more on this shortly)
2. As well as “next” for each property, a “next by distance” where the value is incremented by the distance since the last matching tag. If there is no matching tag then the total number of commits on the repository is used instead.
I have a few notes/queries relating to this. 
We originally did this against an older version of the gradle plugin and I have some tests (which mainly …

Support next by distance and label as number

---

CHANGELOG.md
README.md
docs/configuration-9.4.0.xsd
pom.xml
src/main/java/me/qoomon/gitversioning/commons/GitSituation.java
src/main/java/me/qoomon/gitversioning/commons/GitUtil.java
src/main/java/me/qoomon/maven/gitversioning/Configuration.java
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/gitversioning/commons/GitUtilTest.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

Support setting the `firstParent` option for `git describe`

allow overriding of firstParent in git describe evaluation

---

README.md
src/main/java/me/qoomon/maven/gitversioning/Configuration.java
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

Added a new configuration section for userProperties which are added to the mavenSession.userProperties at startup.
Proposes an alternative to add properties that are not yet defined in the pom (under root or profiles).
A user can decide to define userProperties so he knows exactly what is going to happen with them.
They will be added to the mavenSession from the start and available during the build for processing AND in case a user property is defined that exists somewhere in the pom, the userProperty will take precedence over the existing property as that is how maven handles user-defined properties.
Example
```
<ref type="branch">
...
<properties>
<test.property.1>...</test.property.1>
<test.property.2>...</test.property.2>
</properties>
<userProperties> …
```

Support overwriting properties defined in parent #235

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

The placeholder was misspelled and contained the version segment two
times.

Fix describe.tag.version.label

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

By default, _Eclipse Sisu_ IoC implementation knows all candidates of `org.apache.maven.model.building.ModelProcessor` implementation.
So, there is always `org.apache.maven.model.building.DefaultModelProcessor` in this list (as well as the current `me.qoomon.maven.gitversioning.GitVersioningModelProcessor`).
When a project uses another custom `ModelProcessor` like the [polyglot](https://github.com/takari/polyglot-maven) extension (see [Maven Website](https://maven.apache.org/extensions/index.html)), this list also contains this alternative implementation.
This change allows delegating core methods (`File locatePom( File projectDirectory )` and `Model read(...)`) to the "parent implementation" (defaults to `org.apache.maven.model.building. ModelProcessor` or a custom implementation if …

Delegate Model Processing to parent implementation

---

README.md
src/main/java/me/qoomon/gitversioning/commons/StringUtil.java

My use case is: If branch name is develop, version should be develop-SNAPSHOT. If branch name is feature/JIRA-12345, version should be \~JIRA-12345-SNAPSHOT, so it is alphabeticaly always later (newer). The tilda should be added only if prefix "feature/" is present i.e. ${prefix:+~}.
The problem is, that even if prefix is not defined current implementation creates ${prefix} with empty string, so the overwriting happen. My PR adds possibility to treat empty string as variable not defined.

feat(StringUtil): implement format placeholders closer to _posix parameter expansion_ - i.e. implement optional colon

---

src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
src/test/java/me/qoomon/maven/gitversioning/GitVersioningExtensionIT.java

Currently I have a multi-module project where I use jsonschema2pojo-maven-plugin to generate pojo classes from JSON schemas and I needed to add there a customAnotator from my another module.
Here is a part of the build plugin configuration:
<plugin>
<groupId>io.github.jiri-meluzin</groupId>
<artifactId>jsonschema2pojo-maven-plugin</artifactId>
<version>1.2.2-VFGenericsFix</version>
<dependencies>
<dependency>
<groupId>xxxx.yaml</groupId>
<artifactId>annotator</artifactId>
<version>${project.version}</version>
</dependency>
</dependencies>
<configuration>
<customAnnotator>xxxx.yaml.annotator.HideObjectsWithDefaultValue</customAnnotator>
....
<targetPackage>xxxx.config.globalconfig</targetPackage>
<targetVersion>11</targetVersion>
</configuration>
<executions>
<?m2e execute …

Added support for plugin with dependency from related project

---

README.md
src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java

We need to be able to use a slightly modified configuration in our CI/CD pipeline. Therefore, we added an option to define the configuration file name via command-line arguments / environment variables

feat: added commandline option to define config file name
